name: MIRA on main

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  mira:
    if: ${{ github.event.head_commit.author.name == 'Mirror Admin' }}
    runs-on: self-hosted
    
    env:
      TARGET_URL: ${{ secrets.TARGET_URL }}
      WPSCAN_TOKEN: ${{ secrets.WPSCAN_TOKEN }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: MIRA DAST
        working-directory: .
        run: |
          docker compose pull mira-dast
          docker compose run --rm mira-dast || true

      - name: MIRA SAST
        working-directory: .
        run: |
          docker compose run --rm mira-sast-semgrep

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          pip install requests

      - name: MIRA SCA
        env:
          WPSCAN_TOKEN: ${{ secrets.WPSCAN_TOKEN }}
        run: |
          python mira_sca.py
