name: MIRA on main

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  mira:
    runs-on: self-hosted
    
    env:
      TARGET_URL: ${{ secrets.TARGET_URL }}
      WPSCAN_TOKEN: ${{ secrets.WPSCAN_TOKEN }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

#      - name: Ejecutar SCA
#        working-directory: .
#        run: |
#          docker compose pull mira-sca
#          docker compose run --rm mira-sca

#      - name: MIRA DAST
#        working-directory: .
#        run: |
#          docker compose pull mira-dast
#          docker compose run --rm mira-dast || true

      - name: MIRA SAST
        working-directory: .
        run: |
          docker compose run --rm mira-sast-semgrep
